config/routes.rb
Rails.application.routes.draw do

  patch 'users/downgrade'

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  devise_for :users

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :collaborators
  has_many :wikis
  has_many :wikis, through: :collaborators
  after_initialize { self.role ||= :standard }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  after_create :add_collaborator

  def public?
    !private
  end

  def collaborator(user_id)
    collaborators.find_by(user_id: user_id)
  end

  private

  def add_collaborator
    collaborators.create(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
require 'amount'
include Amount
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Upgrade to Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Upgrading to Premium Account - #{current_user.email}",
      currency: 'usd'
    )
    current_user.premium!
    flash[:notice] = "You have now successfully upgraded to the premium account!"
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki, only: [:index, :create, :destroy]
  def index
    @users = User.all
  end

  def create
    collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    if collaborator.save
      flash[:notice] = "Collaborator added"
    else
      flash[:alert] = "Failed to add collaborator"
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    collaborator = Collaborator.find(params[:id])
    if collaborator.destroy
      flash[:notice] = "Collaborator removed"
    else
      flash[:alert] = "Failed to remove collaborator"
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  private
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    current_user.standard!
    current_user.wikis.update_all(private: false)
    redirect_to root_path, notice: "You were successfully downgraded"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, except: [:index, :new, :create]
  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash.now[:alert] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @wiki.update_attributes(wiki_params)
      redirect_to @wiki, notice: "Wiki was successfully updated."
    else
      flash.now[:alert] = "Error saving wiki. Please try again."
      render :edit
    end
  end

  def destroy
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki. Please try again later"
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def set_wiki
    @wiki = Wiki.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = {
      filter_html: true,
      prettify: true
    }

    extensions = {
      autolink: true,
      quote: true,
      disable_intended_code_blocks: true,
      superscript: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Upgrade to Premium</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%=
  @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%=
  @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>Collaborators</h1>
<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <div class="media-heading">
            <p><%= user.email %></p>
            <% if user.wikis.include?(@wiki) %>
              <%= link_to "Remove", wiki_collaborator_path(@wiki, @wiki.collaborator(user.id)), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home",  welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Wiki", wikis_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, class: 'navbar-link' %>
        <% end %>
      </div>
    </ul>
    <div class="pull-right btn-group">
      <% if user_signed_in? %>
        <% if current_user.standard? %>
          <%= link_to "Upgrade to Premium?", new_charge_path, class: 'btn btn-primary' %>
        <% elsif current_user.premium? %>
          <%= link_to "Downgrade to standard?", users_downgrade_path(current_user), method: :patch, class: 'btn btn-danger', data: { confirm: "All your private wikis will become public if you downgrade" } %>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <br />
    <% if current_user == @wiki.user || current_user.admin?%>
      <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
          <small><%= markdown(wiki.body) %></small>
        </div>
      </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= markdown(@wiki.body) %></p>
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
    </small>
  </div>
  <div class="col-md-4">
    <% if current_user %>
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this wiki?" } %>
    <% end %>
  </div>
</div>